### ISSUE TITLE
为什么各种莫名其妙的问题？求解

### ISSUE THREAD

**Issue by ltshun** [jinyuttt/judt#1]
1.TestClient启动报错：Exception in thread "main" java.lang.NumberFormatException: For input string: "0/0"；
2.我忽略这个报错，结果TestServer报错：警告: Got: 48  java.lang.ArrayIndexOutOfBoundsException: 48
3.TestRecFiles的读取XML写的是读取config.xml，测试程序文件夹里的却是Config.xml,大小写都不在乎的吗？

**Comment by jinyuttt** [comment]
这个是我后面加的

**Comment by jinyuttt** [comment]
我后面空了看看，我应该是正常的。
我的测试是在windows上的，没有区分大小写。

**Comment by ltshun** [comment]
> 我后面空了看看，我应该是正常的。
> 我的测试是在windows上的，没有区分大小写。

好的，谢谢大锅

**Comment by jinyuttt** [comment]
你好，我查看了代码，由于我后面的封装，在文件发送接收这里，测试我写死了，你需要自己修改下进行测试；仿照我的例子就可以了。
我是逐步完成的，但是都是用的同一个包，同一个启动类，可能在测试这里有点乱了。需要你自己生成测试，不能直接使用我的了。

**Comment by ltshun** [comment]
> 你好，我查看了代码，由于我后面的封装，在文件发送接收这里，测试我写死了，你需要自己修改下进行测试；仿照我的例子就可以了。
> 我是逐步完成的，但是都是用的同一个包，同一个启动类，可能在测试这里有点乱了。需要你自己生成测试，不能直接使用我的了。

好的，谢谢，感谢。
